---
- name: Converge
  hosts: all
  become: yes
  become_method: doas
  tasks:
    - name: "Use tleguern.mysql purge.yml"
      include_role:
        name: "ansible-role-mysql"
        tasks_from: purge.yml
