---
- name: Verify
  hosts: all
  gather_facts: false
  become: yes
  become_user: root
  become_method: doas
  tasks:
    - name: Gather MySQL users.
      community.mysql.mysql_info:
        filter: databases,users
        return_empty_dbs: yes
      register: mu
    - assert:
        that:
          - "'appuser' in mu['users']['localhost']"
          - "'appdata' in mu['databases']"
