---
- name: Verify
  hosts: all
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Gather MySQL users.
      community.mysql.mysql_info:
        filter: databases,users
        return_empty_dbs: yes
      register: mu
    - name: Check the size of ibdata1
      stat:
        path: /var/lib/mysql/ibdata1
      register: st
    - assert:
        that:
          - "'appuser' in mu['users']['localhost']"
          - "'appdata' in mu['databases']"
          - "st.stat.size == 10485760"
